### ISSUE TITLE
size reported for "type=dir" headers is 0

### ISSUE THREAD

**Issue by stephen679** [vbatts/go-mtree#12]
version: [0b85ce](https://github.com/vbatts/go-mtree/commit/0b85ce1f8146d3ac7f773975f00666f5026d7ef8)

When collecting values of keywords from a header `hdr` via tar stream in readHeaders(), hdr.FileInfo().Size() returns size 0 when it is `type=dir`.

For example, for `.git` folder:

Actual:      `.git           type=dir size=0 time=1461100246.000000000`
Expected: `.git           type=dir size=4096 time=1461100246.000000000`

**Comment by stephen679** [comment]
Clarification: Size() reports the size of the contents of a particular file, in which when called on a directory, it is expected inside a tar archive, there is nothing in that directory. Instead, what we actually want is the size of the directory structure itself.

**Comment by vbatts** [comment]
i'm not seeing that. Interesting. 
Here is a comparison of upstream mtree and go-mtree
```bash
vbatts@bananaboat ~ (master) $ mtree -c -p ./bin | grep type=dir
.               type=dir mode=0775 nlink=3 size=4096 \
.sync           type=dir mode=0775 nlink=2 size=4096 \
vbatts@bananaboat ~ (master) $ gomtree -c -p ./bin | grep -w dir
. size=4096 type=dir mode=0775 nlink=3 time=1467130505.015551996
.sync size=4096 type=dir mode=0775 nlink=2 time=1386609429.618041696
```

**Comment by stephen679** [comment]
Sorry for the confusion; I haven't run the actual go-mtree command, this is output from printing information about the tar headers within `readHeaders()` in tar.go.

**Comment by vbatts** [comment]
oh. well yes. the tar stream. It will be zero in the tar header. But on disk it will be 4096 bytes. that is a notable translation.

**Comment by stephen679** [comment]
right, but can we just assume that folders on disk will always be 4096 bytes?

**Comment by vbatts** [comment]
very typically the size of the link to the inode, is 4kb. Though, it may be
safer to just not include the `size=` for directories.

**Comment by stephen679** [comment]
hmm, won't that be an issue when we try to create the actual mtree spec and subsequently when we try to validate a file hiearchy with this spec?

**Comment by vbatts** [comment]
if the size= keyword is not present in a `/set` nor for a specific entry,
then it is not validated.

**Comment by stephen679** [comment]
okay sounds like we should leave this keyword out for now. thanks for clarifying.
