### ISSUE TITLE
vis: move govis to library and rewrite it

### ISSUE THREAD

**Issue by cyphar** [vbatts/go-mtree#120]
The current state of `Vis` and `Unvis` is quite ugly. They are a port of `vis(3)` and `unvis(3)` from BSD, which were written in C in the **80s**. As a result, the code is effectively impossible to follow and required hacking around in order to make it work nicely with unicode (because Go is different to C when iterating over strings).

`Vis` and `Unvis` also need to be **much** better tested -- especially with unicode input.

**Comment by vbatts** [comment]
:thumbs_up:

**Comment by cyphar** [comment]
After thinking some more about some aspects of all of this encoding. My current "fix" for unicode (#119) subtly broke `\x__`-style strings. Don't worry, it won't get hit by any of our encoding code. I'm working on a proper fix for it though.

**Comment by cyphar** [comment]
I'm currently working on this in https://github.com/cyphar/govis.

**Comment by vbatts** [comment]
Hah right on

**Comment by cyphar** [comment]
Alright. Currently my `Vis` implementation has pretty solid integration and other tests. It also is `unicode` aware while also encoding unicode characters in a way that makes sure that legacy `unvis` implementations should "do the right thing" even though they don't understand unicode.

Namely this means that `Vis` will output ASCII and nothing else.

**Comment by vbatts** [comment]
neat. Next step?

**Comment by cyphar** [comment]
Well, there are two options:

1. We keep `govis` as a separate library, and add it as a dependency to `go-mtree`. The next step would be for me to tag `govis` and then rewrite the `go-mtree` code to import it.
2. We move `govis` into `pkg/govis` inside `go-mtree` so that there's no dependency issue. The next steps would be to move everything in and rewrite `go-mtree` to import it.

Which would you prefer?

**Comment by vbatts** [comment]
honestly ./pkg/ for now. Can you preserve your commit history?

**Comment by cyphar** [comment]
yup, will do
