### ISSUE TITLE
mtree no longer detects xattr changes

### ISSUE THREAD

**Issue by cyphar** [vbatts/go-mtree#140]
You can test this fairly simply:

```
% mkdir somedir && touch somedir/file
% gomtree -c -f 1.mtree -p somedir
% xattr -w user.something something somedir/file
% gomtree -f 1.mtree -p somedir
% echo $?
0
```

This isn't caused by the specKeywords code, it happens even if there are already xattrs (or even if you remove existing `xattrs`). This broke with `v0.4.0`.

**Comment by cyphar** [comment]
I found this while working on openSUSE/umoci#176.

**Comment by cyphar** [comment]
Bisecting finds that ed464af779f00235b602f7a4fa2e50a0b079d862 caused this.

**Comment by vbatts** [comment]
In that ocean of a patch. Alrighty, I'll take a look

**Comment by cyphar** [comment]
@vbatts Already fixed. Submitting a PR now.

**Comment by vbatts** [comment]
u da bes
