### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by tych0** [vbatts/go-mtree#158]
It's been a bit since a release, and because of the golang default of latest-released-version, I have to put:

```
replace github.com/vbatts/go-mtree v0.4.4 => github.com/vbatts/go-mtree v0.4.5-0.20190122034725-8b6de6073c1a
```

Everywhere to use some of the new code. It would be nice to get rid of this :)

**Comment by vbatts** [comment]
https://github.com/vbatts/go-mtree/releases/tag/v0.5.0 !

**Comment by tych0** [comment]
On Thu, Apr 30, 2020 at 03:52:57PM -0700, Vincent Batts wrote:
> https://github.com/vbatts/go-mtree/releases/tag/v0.5.0 !

Grazie!
