### ISSUE TITLE
The option of specifying the option `-f` twice is not implemented

### ISSUE THREAD

**Issue by zachawilson** [vbatts/go-mtree#159]
I believe this is a feature request.

I have attempted to compare two specification files with
`gomtree -f first.txt -f second.txt`

The result of this seems that the second option is ignored.

This is the capability that I am referencing:
https://www.freebsd.org/cgi/man.cgi?mtree(8)
> -f	spec	
> 			
> 			Read the specification from file, instead of from the
> 			standard input.
> 
> 			If this	option is specified twice, the two specifica-
> 			tions are compared to each other rather	than to	the
> 			file hierarchy.	 The specifications will be sorted
> 			like output generated using -c.	 The output format in
> 			this case is somewhat reminiscent of comm(1), having
> 			"in first spec only", "in second spec only", and "dif-
> 			ferent"	columns, prefixed by zero, one and two TAB
> 			characters respectively.  Each entry in	the "differ-
> 			ent" column occupies two lines,	one from each specifi-
> 			cation.

The addition of this capability would be valuable as part if at all possible.

**Comment by vbatts** [comment]
That would be valuable. And that is how the BSD version reads. Hrm.

Current flag parser we use doesn't support multiple flags, but I've mulled on switching to a different cli backend like cobra or urfave/cli.

**Comment by vbatts** [comment]
I've just switched flag parsing to using `github.com/urfave/cli/v2`, and now that `-f` file flag can more easily be changed to a `&cli.StringSliceFlag{}` for multiple args. Next will be comparing the two directory hierarchies
