### ISSUE TITLE
[bug] fails validating on broken symlink

### ISSUE THREAD

**Issue by vbatts** [vbatts/go-mtree#33]
```bash
$ sudo /home/vbatts/bin/gomtree -c -p fedora/ -k mode,uid,gid,size,sha512digest > fedora.mtree
$ sudo /home/vbatts/bin/gomtree -f ./fedora.mtree -p fedora/
2016/07/20 23:00:38 open etc/alternatives/cifs-idmap-plugin: no such file or directory
$ sudo file fedora/etc/alternatives/cifs-idmap-plugin
fedora/etc/alternatives/cifs-idmap-plugin: broken symbolic link to /usr/lib64/cifs-utils/cifs_idmap_sss.so
```

**Comment by stephen679** [comment]
[broken_symlinks](https://github.com/stephen679/go-mtree/tree/evaluating_symlink)

Default behavior should just be to `lstat` a non-regular file. As for what to do when we _do_ want to follow symlinks, this raises the discussion about design for go-mtree functionality with extra options (i.e, following symlinks, modifying files, ignoring everything but directories, etc.)

**Comment by stephen679** [comment]
would we be able to easily follow symlinks in tar creation/validation?

**Comment by vbatts** [comment]
I'm realizing that this is not particularly due to a broken symlink, but that any keyword function that is doing opening a file for read, should only open regular files (not symlinks).

**Comment by vbatts** [comment]
@stephen679 are you going to add a PR of your branch?

**Comment by stephen679** [comment]
just pushed it, #62
