### ISSUE TITLE
[bug] digest synonyms on validation

### ISSUE THREAD

**Issue by stephen679** [vbatts/go-mtree#60]
By defining `sha256` and `sha256digest` with the same function, we are able to create a manifest with the same output by doing `gomtree -c -p . -K sha256` and `gomtree -c -p . -K sha256digest`.

However, when we validate a manifest, we must do the same, in that if we specified `gomtree` to validate with `-k sha256`, and then come across `sha256digest` in the validation manifest, the digest is still validated. This is because when we do the validation, we check if the keyword we find in the manifest is in the set of keywords that the user specifies.

**Comment by vbatts** [comment]
This is fixed with #92
