### ISSUE TITLE
tar: generates incomplete manifests

### ISSUE THREAD

**Issue by cyphar** [vbatts/go-mtree#77]
If you do something like this:

```
% gomtree -T a.tar -c
#          user: cyphar
#       machine: gordon
#          tree: <user specified tar archive>
#          date: Mon Oct 31 04:35:03 2016

# .
. type=dir
    tmpfile size=12 type=file uid=1000 gid=100 mode=0644 tar_time=100.000000000

# testdir
/set type=file mode=0664 uid=1000 gid=100
testdir type=dir mode=0755 tar_time=100.000000000
    anotherfile size=3 mode=0644 tar_time=100.000000000
# testdir
..
# .
..

```

You can clearly see that `/set` is in the wrong place. Not to mention that the directories are incorrectly labeled and `.` is completely unlabeled. This is breaking the comparison tests for #48.

**Comment by cyphar** [comment]
For comparison here's the output when using `-p`:

```
% gomtree -p /tmp
#          user: cyphar
#       machine: gordon
#          tree: /tmp/test-compare-tar437148820
#          date: Mon Oct 31 04:37:01 2016

# .
/set type=file nlink=1 mode=0664 uid=1000 gid=100
. size=28 type=dir mode=0700 time=100.000000000
    tmpfile size=12 mode=0644 time=100.000000000

# testdir
testdir size=22 type=dir mode=0755 time=100.000000000
    anotherfile size=3 mode=0644 time=100.000000000
..
..
```

**Comment by stephen679** [comment]
If I recall correctly, I was running into this same issue when I was developing this code and @vbatts and I were discussing about how a tar file could be generated either with a regular directory (i.e, tar -cf <folder>) or as a collection of files (tar -cf <file1> <file2> etc.). As a result it is not always certain that your "." directory will have attributes associated with it (for example if you generate a tar with the second method), so I decided to just always put files under a ".", that might not necessarily have a `/set` to go along with it.

Of course, this can be improved by being able to distinguish when the "." directory is actually meaningful :)

**Comment by cyphar** [comment]
Tar files don't need to have a `.` directory. We should only include one if it was actually in the archive, and we should handle it the same way as a regular directory. However, currently there's a lot of complex code in `tar.go` that I don't really want to touch. I'm going to just leave it for now (and ignore the issues with `Compare` since they're caused by the tar handling.

**Comment by vbatts** [comment]
tar files don't have to have a `.` entry, but it is implied. This was an election I made. And that is why it only includes a single keyword of `type=dir`, so nothing else is checked (like ownership, etc). If the tar archive is created like `tar cf /tmp/a.tar .` then it _will_ have an entry for the root directory, and should have more keywords.

The `/set` being in a different place is not an issues AFAICS. mtree output can have `/set` and `/unset` scattered about.

I think this is a non-issue and is not breaking anything. If you find that it is breaking something, then lets create a `./test/cli/` to trigger it so we can ensure it doesn't happen.

**Comment by cyphar** [comment]
@vbatts It's breaking the `Compare` API. However, a possible solution to this problem is to create a function that checks whether a discrepancy between two manifests is okay (the `type=dir` trick you mentioned is actually what is causing some of the error-skipping code in the `Compare` tests to have to exist).

Basically, you'd just have to iterate through all of the KeyDeltas for a particular InodeDelta and see whether any are `Modified` rather than `Extra` or `Missing`. We could make it a function like `IsModified(mtree.InodeDelta)`.

Another option is that we modify `Compare` so that it doesn't do comparisons if a key is missing in either manifest (in other words we only compare **modified** keys). That can also work, and I'd understand if you want to go in that direction.

**Comment by cyphar** [comment]
Ah, scratch the above -- you fixed the issues after your recent changes. I'll fix up `compareEntry` to remove some of the old logic that no longer is necessary.

**Comment by vbatts** [comment]
Right on
