### ISSUE TITLE
Missing files not reported

### ISSUE THREAD

**Issue by baude** [vbatts/go-mtree#90]
I'm seeing two errors related to verification of a manifest:

* When you create an mtree manifest for foo1 and then use that manifest to verify foo2, which is missing missing files that foo1 has, go-mtree does not report these.
* When you create an mtree manifest for foo and then use the manifest to verify foo2, where foo2 has files foo1 does not, go-mtree does not report these.

```
#!/bin/bash
set -x
set -e

name=$(basename $0)
root=$1
gomtree=/home/bbaude/bin/gomtree
left=$(mktemp -d /tmp/go-mtree.XXXXXX)
right=$(mktemp -d /tmp/go-mtree.XXXXXX)

echo "[${name}] Running in ${left} and ${right}"

touch ${left}/one
touch ${left}/two
cp -a ${left}/one ${right}/
ls -lR ${left}
ls -lR ${right}

$gomtree -K "sha256digest" -p ${left} -c > /tmp/left.mtree
$gomtree -k "sha256digest" -p ${right} -f /tmp/left.mtree
echo $?
rm -fr ${left} ${right}
```

**Comment by cyphar** [comment]
This has been fixed by #97 AFAICS. The reason I didn't implement it in the BSD formatter is because I wasn't sure what the output format should look like.
