### ISSUE TITLE
make .cli.test doesn't error out

### ISSUE THREAD

**Issue by cyphar** [vbatts/go-mtree#98]
Because of how the `.cli.test` rule is written, `make` will not exit with an error. I noticed this while adding tests to #96. It's a little concerning to be honest.

Also, I don't understand why you've implemented the `touch .cli.test` code. Why should testing ever be skipped?

**Comment by vbatts** [comment]
fixed in #99

And I've added the `touch $@` because it depends on the build, and the build depends on the source files. If it ran successfully and nothing has changed then no need to retest. If anything has changed, then it all gets done again.
